=== danmaq/nue/project/trunk/skin/nue.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xml:lang="ja"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:xhtml="http://www.w3.org/1999/xhtml">
	<xsd:import namespace="http://www.w3.org/1999/xhtml"
		schemaLocation="http://www.w3.org/MarkUp/SCHEMA/xhtml11.xsd"/>

	<xsd:element name="body" type="BodyType" />
	<xsd:element name="user" type="UserType" />
	<xsd:element name="search" type="SearchType" />
	<xsd:element name="topic" type="TopicType" />
	<xsd:element name="form" type="FormType" />
	<xsd:element name="p" type="ParagraphType" />
	<xsd:complexType name="BodyType">
		<xsd:sequence>
			<xsd:attribute name="title" type="xsd:string" use="required" />
			<xsd:element ref="user" maxOccurs="1" />
			<xsd:element ref="search" maxOccurs="1" />
			<xsd:element ref="topic" minOccurs="1" />
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="UserType">
		<xsd:sequence>
			<xsd:attribute name="id" type="xsd:string" />
			<xsd:attribute name="name" type="xsd:string" />
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="SearchType">
		<xsd:sequence>
			<xsd:attribute name="tag" type="xsd:string" />
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="TopicType">
		<xsd:sequence>
			<xsd:attribute name="title" type="xsd:string" use="required" />
			<xsd:element ref="p" />
			<xsd:element ref="form" />
			<xsd:element ref="id" />
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="form">
		<xsd:sequence>
			<xsd:attribute name="action" type="xsd:anyURI" use="required" />
			<xsd:element ref="p" />
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="p">
		<xsd:sequence>
			<xsd:attribute name="title" type="xsd:string" />
			<xsd:element ref="xhtml:a" />
			<xsd:element ref="xhtml:abbr" />
			<xsd:element ref="xhtml:bdo" />
			<xsd:element ref="xhtml:br" />
			<xsd:element ref="xhtml:cite" />
			<xsd:element ref="xhtml:code" />
			<xsd:element ref="xhtml:dfn" />
			<xsd:element ref="xhtml:em" />
			<xsd:element ref="xhtml:kbd" />
			<xsd:element ref="xhtml:mark" />
			<xsd:element ref="xhtml:q" />
			<xsd:element ref="xhtml:ruby" />
			<xsd:element ref="xhtml:samp" />
			<xsd:element ref="xhtml:small" />
			<xsd:element ref="xhtml:span" />
			<xsd:element ref="xhtml:strong" />
			<xsd:element ref="xhtml:sub" />
			<xsd:element ref="xhtml:sup" />
			<xsd:element ref="xhtml:time" />
			<xsd:element ref="xhtml:var" />
			<xsd:element ref="xhtml:wbr" />

			<xsd:element ref="xhtml:del" />
			<xsd:element ref="xhtml:ins" />

			<xsd:element ref="xhtml:audio" />
			<xsd:element ref="xhtml:canvas" />
			<xsd:element ref="xhtml:embed" />
			<xsd:element ref="xhtml:iframe" />
			<xsd:element ref="xhtml:img" />
			<xsd:element ref="xhtml:map" />
			<xsd:element ref="xhtml:object" />
			<xsd:element ref="xhtml:progress" />
			<xsd:element ref="xhtml:video" />

			<xsd:element ref="xhtml:button" />
			<xsd:element ref="xhtml:datalist" />
			<xsd:element ref="xhtml:fieldset" />
			<xsd:element ref="xhtml:input" />
			<xsd:element ref="xhtml:label" />
			<xsd:element ref="xhtml:meter" />
			<xsd:element ref="xhtml:output" />
			<xsd:element ref="xhtml:select" />
			<xsd:element ref="xhtml:textarea" />
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>

=== danmaq/nue/project/trunk/skin/sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<body title="ページ タイトル" site="ブログ タイトル" ver="0.0.21"
	xmlns:xhtml="http://www.w3.org/1999/xhtml"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="./skin/nue.xsd">
	<!-- ver要素にはNUEのバージョンが格納されています。正規表現で表すと\d+\.\d+\.\d+です -->

	<user id='hogehoge' name='ほげ太郎' />
	<!-- ログイン時のみ挿入されます -->

	<topic title="トピック タイトル">
		<p>
			文章。ここにHTMLのインライン要素が挿入できます。
			(ただし、xhtml名前空間を使用すること)
			例: <xhtml:br />
		</p>
		<p title="段落にもタイトルを設定することが可能です">
			1トピック内に複数の段落を設定できます。
		</p>
	</topic>
	<topic title="複数トピックを作成可能です">
		<p>
			このようなXMLデータがNUEから出力されますので、これに対応するXSLを作成して
			お好みのデザイン・レイアウトへ調整してください。
		</p>
	</topic>
</body>
